### ISSUE TITLE
How to extend this example to support offline use (without a signed-in user)

### ISSUE THREAD

**Issue by TomislavSmvc** [Azure-Samples/ms-identity-java-webapi#22] opened 2021-08-02 19:16 UTC
What would be the correct way to enable this example to support calling Graph calls in the background, as a automatic job, for instance using the @Scheduled annotation.
I would like my users to first login and initialize the tokens, and then my system can import emails from their accounts into my own database every few hours

I actually got it to work by making a seperate OboAuthProvider. There i would retrieve a previously cached token:

```
@Override
    public CompletableFuture<String> getAuthorizationTokenAsync(URL requestUrl) {
        try {
            IAuthenticationResult authResult;

            //loadedCacheKey is initialized elsewhere
            String cachedTokens = cacheManager.getCache("tokens").get(loadedCacheKey, String.class);
            if(cachedTokens == null){
                throw new AuthException("No cached token present", null);
            }
            else{
                ConfidentialClientApplication application = ConfidentialClientApplication
                        .builder(clientId, ClientCredentialFactory.createFromSecret(secret))
                        .authority(authority)
                        .build();

                application.tokenCache().deserialize(cachedTokens);
                SilentParameters silentParameters = SilentParameters.builder(Collections.singleton(scope)).build();
                authResult = application.acquireTokenSilently(silentParameters).join();
            }

            return CompletableFuture.completedFuture(authResult.accessToken());
        }
        catch (Exception ex){
            throw new AuthException(String.format("Error acquiring token from AAD: %s", ex.getMessage()), ex.getCause());
        }
    }
```

And this actually works for less then an hour. But after an hour or so i get the exception:
`com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache`

As long as the token is valid, everything works ok, but once the token expires i get the above exception. How am i supposed to refresh my existing token?

And i just dont know what i am doing wrong. I made sure that both app registtrations include the "offline" permissions and that the users actually consented to it. I also made sure that the CacheManager has a longer expiration period.

I know that this is off-topic, but i just dont see what went wrong.

**Comment by TomislavSmvc** [comment] 2021-08-03 12:49
I managed to figure out how to get the refresh token. (just make sure that both app registrations have the offline_access permision and you MUST explicitly request the offline_access scope, it is not enough to just request the .default scope).

But i still get the same error, i looked a bit into the MSAL code and it turns out that it is first checking if the access token is expired, and after that if it should be refreshed.
That means, when the token is expired, it throws an exception and it will not even attempt to refresh even if i have a refresh token.

I am using:
msal4j : 1.9.1
microsoft-graph:3.2.0
spring-security-oauth2:2.3.6.RELEASE

Is this bug fixed in a later version?

**Comment by sangonzal** [comment] 2021-08-03 21:18
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/426

**Closed by sangonzal** 2021-08-03 21:18 UTC
